name: grGIA_seismicity_test

channels:
  - anaconda
  - conda-forge

dependencies:
  - python=3.10
  - jupyter
  - obspy
  - numpy 
  - pandas 
  - scikit-learn
  - seaborn
  - scipy
  - cartopy
  - shapely
  - geopandas